env:
  browser: true
  node: true
  es6: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier/@typescript-eslint"
  - "plugin:prettier/recommended"
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - "prettier"
rules:
  "@typescript-eslint/explicit-module-boundary-types": "off"
  "@typescript-eslint/no-explicit-any": "off"
  "@typescript-eslint/ban-ts-comment": "off"
  "@typescript-eslint/no-namespace": "off"